In [40]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import scipy.special as sp

In [26]:
a = np.zeros([3, 2])

In [79]:
class NeuralNetwork:
    def __init__(self, input_nodes, hidden_nodes, output_nodes, learning_rate):
        self.inodes = input_nodes
        self.hnodes = hidden_nodes
        self.onodes = output_nodes
        self.lr = learning_rate
        self.wih = np.random.normal(0.0, pow(self.inodes, -0.5), (self.hnodes, self.inodes))
        self.who = np.random.normal(0.0, pow(self.hnodes, -0.5), (self.onodes, self.hnodes))
        self.act_fn = lambda x: sp.expit(x)
        

    def train(self, inputs_list, targets_list):
        targets = np.array(target, ndmin=2).T
        inputs, hidden_outputs, final_outputs = self.query(inputs_list)

        output_errors = targets - final_outputs
        hidden_errors = numpy.dot(self.who.T, output_errors)

        self.who += self.lr * numpy.dot((output_errors * final_outputs * (1 - final_outputs)), numpy.transpose(hidden_outputs))
        self.wih += self.lr * numpy.dot((hidden_errors * hidden_outputs * (1 - hidden_outputs)), numpy.transpose(inputs))
        
    
    def query(self, inputs_list): 
        inputs = numpy.array(inputs_list, ndmin=2).T
        
         # Calculate signals into and out of hidden layer
        hidden_inputs = np.dot(self.wih, inputs)
        hidden_outputs = self.act_fn(hidden_inputs)
        
        # Calculate signals into and out of output layer
        final_inputs = np.dot(self.who, hidden_outputs)
        final_outputs = self.act_fn(final_inputs)

        return inputs, hidden_outputs, final_outputs

In [70]:
input_nodes = 3
hidden_nodes = 3
output_nodes = 3

learning_rate = 0.3

nn = NeuralNetwork(input_nodes, hidden_nodes, output_nodes, learning_rate)

In [71]:
nn.query([1.0, 0.5, -1.5])

array([0.48389035, 0.44878913, 0.4952243 ])

In [61]:
np.random.rand(3, 3) - 0.5 # broadcasting so that we don't have have to expand the scalar to match the size of the vector

array([[ 0.44991075,  0.44164515,  0.08760796],
       [-0.4408309 ,  0.18734701, -0.1783851 ],
       [ 0.08414233, -0.05492229,  0.27456323]])

In [62]:
inputs_list = [0.2, 0.3, 0.4]

In [77]:
print(np.array(inputs_list, ndmin=2))
print(np.array(inputs_list, ndmin=2).T.T)

[[0.2 0.3 0.4]]
[[0.2 0.3 0.4]]


In [76]:
np.array(inputs_list, ndmin=2) - np.array(inputs_list, ndmin=2)

array([[0., 0., 0.]])